services:
  client:
    image: e-uni-manager-client-development
    build:
      dockerfile: Dockerfile.Development
    volumes:
      - /app/node_modules
      - ./EUniManager.Client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
      
  api:
    image: e-uni-manager-api-development
    build:
      dockerfile: Dockerfile.Development
    volumes:
      - ./EUniManager.Server:/app
      - ./EUniManager.Server/src/Presentation/EUniManager.Api/https:/https:ro
    environment:
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true
      - DOTNET_WATCH_SUPPRESS_MSBUILD_INCREMENTALISM=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}